### ISSUE TITLE
更新后配置文件不变的问题

### ISSUE THREAD

**Issue by Discreater** [vfyjxf/NotEnoughCharacters#1]
比如说本地有旧版本的配置文件，新版本往列表里添加了一个新的条目，安装新版本之后，读取的还是旧的配置文件，这时候只能手动更新配置文件才能真正的更新。

一个想法是像 Jech 一样，分为可配置列表（包括黑名单）和固定列表。mod更新只加固定列表的内容，用户的修改只在可配置列表中生效。

**Comment by vfyjxf** [comment]
整好了，把jech配置文件系统挪了过来
