### ISSUE TITLE
gtnh 新版本的接口终端不支持nec力！

### ISSUE THREAD

**Issue by miaowwwwww** [vfyjxf/NotEnoughCharacters#5]
gtnh 新版本的接口终端不支持nec力！
下面是他们做的改动
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/394     
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/160

**Comment by SafariXiu** [comment]
++++++++++++++++++1
