### ISSUE TITLE
gtnh 2.4.2新版本的接口终端的接口名搜索好像没有支持，是1.5.1的nec

### ISSUE THREAD

**Issue by CCYF78** [vfyjxf/NotEnoughCharacters#6]
![image](https://github.com/vfyjxf/NotEnoughCharacters/assets/150128194/acaa4877-0318-493c-9686-cbcd40fe70bf)
![image](https://github.com/vfyjxf/NotEnoughCharacters/assets/150128194/6cb893cd-cfcf-4bc7-9332-871b007ee7c4)

**Comment by vfyjxf** [comment]
fix it just now
